### ISSUE TITLE
Bot interactions fail

### ISSUE THREAD

**Issue by ogazit** [bra1n/judgebot#193]
We first noticed this with hangman, where when we click on a letter we always just get the message that "this interaction failed". It's also true on card searches, and has been for a few weeks now.

**Comment by multimeric** [comment]
@bra1n could you have a look at the logs please? Maybe give it a restart?

**Comment by bra1n** [comment]
> @bra1n could you have a look at the logs please? Maybe give it a restart?

There seems to be only one error being thrown repeatedly:
```
TypeError: channel.isTextBased is not a function
    at InteractionCreateAction.handle (/home/brain/judgebot/node_modules/discord.js/src/client/actions/InteractionCreate.js:46:33)
    at Object.module.exports [as INTERACTION_CREATE] (/home/brain/judgebot/node_modules/discord.js/src/client/websocket/handlers/INTERACTION_CREATE.js:4:36)
    at WebSocketManager.handlePacket (/home/brain/judgebot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:352:31)
    at WebSocketShard.onPacket (/home/brain/judgebot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:481:22)
    at WebSocketShard.onMessage (/home/brain/judgebot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:321:10)
    at WebSocket.onMessage (/home/brain/judgebot/node_modules/ws/lib/event-target.js:199:18)
    at WebSocket.emit (node:events:513:28)
    at Receiver.receiverOnMessage (/home/brain/judgebot/node_modules/ws/lib/websocket.js:1178:20)
    at Receiver.emit (node:events:513:28)
    at Receiver.dataMessage (/home/brain/judgebot/node_modules/ws/lib/receiver.js:528:14)
```
It also seems to crash the bot whenever it happens, meaning there were a lot of restarts already recently. 😉

**Comment by multimeric** [comment]
It must be that discord broke the API in some way. Seems like I can just bump discord.js: https://github.com/discordjs/discord.js/issues/9295.

**Comment by icy-** [comment]
hi, is there any update on this one?  Game starts fine (easy/medium etc)  but any button click results in "This interaction failed" and the game will eventually time out with its default 3minutes  
![image](https://user-images.githubusercontent.com/236808/236969868-edd2c947-3016-49b9-99fc-aec67fe126db.png)

**Comment by Holydemonics** [comment]
Hi, I know this is old but was a solution to this found or is there something on my server breaking the hangman interaction?

**Comment by multimeric** [comment]
I think it's just a bug I haven't got around to fixing yet. But I'd welcome a PR from someone else
