### ISSUE TITLE
"The application did not respond"

### ISSUE THREAD

**Issue by KingSupernova31** [bra1n/judgebot#195]
Judgebot seems to be down for rules queries; using /cr consistently returns "The application did not respond".

**Comment by multimeric** [comment]
@bra1n

**Comment by bra1n** [comment]
@multimeric there seems to be an issue with some of the bot features. Browsing the "pages" of a card lookup returns this error for example:
```
0|judgebot  | TypeError: channel.isTextBased is not a function
0|judgebot  |     at InteractionCreateAction.handle (/home/brain/judgebot/node_modules/discord.js/src/client/actions/InteractionCreate.js:46:33)
0|judgebot  |     at Object.module.exports [as INTERACTION_CREATE] (/home/brain/judgebot/node_modules/discord.js/src/client/websocket/handlers/INTERACTION_CREATE.js:4:36)
0|judgebot  |     at WebSocketManager.handlePacket (/home/brain/judgebot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:352:31)
0|judgebot  |     at WebSocketShard.onPacket (/home/brain/judgebot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:481:22)
0|judgebot  |     at WebSocketShard.onMessage (/home/brain/judgebot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:321:10)
0|judgebot  |     at WebSocket.onMessage (/home/brain/judgebot/node_modules/ws/lib/event-target.js:199:18)
0|judgebot  |     at WebSocket.emit (node:events:513:28)
0|judgebot  |     at Receiver.receiverOnMessage (/home/brain/judgebot/node_modules/ws/lib/websocket.js:1178:20)
0|judgebot  |     at Receiver.emit (node:events:513:28)
0|judgebot  |     at Receiver.dataMessage (/home/brain/judgebot/node_modules/ws/lib/receiver.js:528:14)
```

**Comment by multimeric** [comment]
@bra1n Weird, I'll have a look. Did you do anything that might have updated the dependencies on the prod server?

@KingSupernova31 What command triggered the error?

**Comment by bra1n** [comment]
> @bra1n Weird, I'll have a look. Did you do anything that might have updated the dependencies on the prod server?

No, I have literally not touched any part of the code or server in at least half a year, if not more. :grimacing:

**Comment by Lohoris** [comment]
I'm getting this error every time I click on the icons at the bottom (the two arrows and the 🔍)

**Comment by KingSupernova31** [comment]
> @KingSupernova31 What command triggered the error?

@multimeric /cr triggered the error, as mentioned in the post. It's not happening for me anymore though.
