### ISSUE TITLE
!card westvale abbey doesnt work

### ISSUE THREAD

**Issue by bra1n** [bra1n/judgebot#64]
bug

**Comment by bra1n** [comment]
Broken again, dang Scryfall API...
```
Nov 20 11:14:24 judgebot app/bot.1: [ERROR] [card] - TypeError: Cannot read property 'small' of undefined 
Nov 20 11:14:24 judgebot app/bot.1:     at resolve (/app/modules/card.js:244:49) 
Nov 20 11:14:24 judgebot app/bot.1:     at Promise (<anonymous>) 
Nov 20 11:14:24 judgebot app/bot.1:     at MtgCardLoader.generateEmbed (/app/modules/card.js:205:16) 
Nov 20 11:14:24 judgebot app/bot.1:     at Promise.all.then (/app/modules/card.js:341:22) 
Nov 20 11:14:24 judgebot app/bot.1:     at <anonymous> 
Nov 20 11:14:24 judgebot app/bot.1:     at process._tickCallback (internal/process/next_tick.js:188:7)
```
